kind: Deployment
apiVersion: apps/v1
metadata:
  name: chart
  labels:
    app: chart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chart
  template:
    metadata:
      labels:
        app: chart
    spec:
      containers:
      - name: chart
        image: jgaonaakm/ovfrtvizchart:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
  